import { describe, it, expect } from "vitest";
import { client, transport, callTool } from "../../client";

describe("item-service", () => {
    it("item-service-get-languages", async () => {
        await client.connect(transport);
        const result = await callTool(client, "item-service-get-languages", {});
        const json = JSON.parse(result.content[0].text);
        expect(json).toMatchObject([
            {
                ItemID: "af584191-45c9-4201-8740-5409f4cf8bdd",
                ItemName: "en",
                ItemPath: "/sitecore/system/Languages/en",
                ParentID: "64c4f646-a3fa-4205-b98e-4de2c609b60f",
                TemplateID: "f68f13a6-3395-426a-b9a1-fa2dc60d94eb",
                TemplateName: "Language",
                CloneSource: null,
                ItemLanguage: "en",
                ItemVersion: "1",
                DisplayName: "en",
                HasChildren: "False",
                ItemIcon: expect.any(String),
                ItemMedialUrl: "/-/icon/Office/48x48/flag_generic.png.aspx",
                ItemUrl: "~/link.aspx?_id=AF58419145C9420187405409F4CF8BDD&amp;_z=z",
                "Base Culture": "",
                "Fallback Region Display Name": "",
                Charset: "",
                "Code page": "",
                Dictionary: "en-US.tdf",
                Encoding: "",
                "Fallback Language": "",
                Iso: "en",
                "Regional Iso Code": "",
                "WorldLingo Language Identifier": "",
            },
            {
                ItemID: "92b779ae-627d-4e6f-8690-0063d914a942",
                ItemName: "fr-CA",
                ItemPath: "/sitecore/system/Languages/fr-CA",
                ParentID: "64c4f646-a3fa-4205-b98e-4de2c609b60f",
                TemplateID: "f68f13a6-3395-426a-b9a1-fa2dc60d94eb",
                TemplateName: "Language",
                CloneSource: null,
                ItemLanguage: "en",
                ItemVersion: "1",
                DisplayName: "fr-CA",
                HasChildren: "False",
                ItemIcon: expect.any(String),
                ItemMedialUrl: "/-/icon/Office/48x48/flag_generic.png.aspx",
                ItemUrl: "~/link.aspx?_id=92B779AE627D4E6F86900063D914A942&amp;_z=z",
                "Base Culture": "",
                "Fallback Region Display Name": "",
                Charset: "iso-8859-1",
                "Code page": "65001",
                Dictionary: "",
                Encoding: "utf-8",
                "Fallback Language": "en",
                Iso: "fr",
                "Regional Iso Code": "fr-CA",
                "WorldLingo Language Identifier": "",
            },
            {
                ItemID: "3694025f-799b-4f7b-98b9-97d569550aed",
                ItemName: "ja-JP",
                ItemPath: "/sitecore/system/Languages/ja-JP",
                ParentID: "64c4f646-a3fa-4205-b98e-4de2c609b60f",
                TemplateID: "f68f13a6-3395-426a-b9a1-fa2dc60d94eb",
                TemplateName: "Language",
                CloneSource: null,
                ItemLanguage: "en",
                ItemVersion: "1",
                DisplayName: "ja-JP",
                HasChildren: "False",
                ItemIcon: expect.any(String),
                ItemMedialUrl: "/-/icon/Office/48x48/flag_generic.png.aspx",
                ItemUrl: "~/link.aspx?_id=3694025F799B4F7B98B997D569550AED&amp;_z=z",
                "Base Culture": "",
                "Fallback Region Display Name": "",
                Charset: "iso-2022-jp",
                "Code page": "65001",
                Dictionary: "",
                Encoding: "utf-8",
                "Fallback Language": "en",
                Iso: "ja",
                "Regional Iso Code": "ja-JP",
                "WorldLingo Language Identifier": "",
            },
        ]);
    });
});